#!/usr/bin/env python3
import argparse
import pathlib
import re
import sys


KERNELS = [
    {
        "name": "hrx_add_f32",
        "source": "add_f32.hip.cpp",
        "format": None,
        "binding_count": 3,
        "constants_size": 8,
        "workgroup_size": (256, 1, 1),
    },
    {
        "name": "hrx_mul_f32",
        "source": "mul_f32.hip.cpp",
        "format": None,
        "binding_count": 3,
        "constants_size": 8,
        "workgroup_size": (256, 1, 1),
    },
    {
        "name": "hrx_add_f32_broadcast",
        "source": "add_f32_broadcast.hip.cpp",
        "format": None,
        "binding_count": 3,
        "constants_size": 112,
        "workgroup_size": (256, 1, 1),
    },
    {
        "name": "hrx_mul_f32_broadcast",
        "source": "mul_f32_broadcast.hip.cpp",
        "format": None,
        "binding_count": 3,
        "constants_size": 112,
        "workgroup_size": (256, 1, 1),
    },
    {
        "name": "hrx_div_f32_broadcast",
        "source": "div_f32_broadcast.hip.cpp",
        "format": None,
        "binding_count": 3,
        "constants_size": 112,
        "workgroup_size": (256, 1, 1),
    },
    {
        "name": "hrx_scale_f32",
        "source": "scale_f32.hip.cpp",
        "format": None,
        "binding_count": 2,
        "parameter_count": 5,
        "constants_size": 16,
        "workgroup_size": (256, 1, 1),
    },
    {
        "name": "hrx_silu_f32",
        "source": "unary_f32.hip.cpp",
        "format": None,
        "binding_count": 2,
        "constants_size": 8,
        "workgroup_size": (256, 1, 1),
    },
    {
        "name": "hrx_sigmoid_f32",
        "source": "unary_f32.hip.cpp",
        "format": None,
        "binding_count": 2,
        "constants_size": 8,
        "workgroup_size": (256, 1, 1),
    },
    {
        "name": "hrx_softplus_f32",
        "source": "unary_f32.hip.cpp",
        "format": None,
        "binding_count": 2,
        "constants_size": 8,
        "workgroup_size": (256, 1, 1),
    },
    {
        "name": "hrx_swiglu_f32",
        "source": "unary_f32.hip.cpp",
        "format": None,
        "binding_count": 3,
        "constants_size": 8,
        "workgroup_size": (256, 1, 1),
    },
    {
        "name": "hrx_clamp_f32",
        "source": "clamp_f32.hip.cpp",
        "format": None,
        "binding_count": 2,
        "constants_size": 16,
        "workgroup_size": (256, 1, 1),
    },
]


def hsaco_name_for_source(source):
    if source.endswith(".hip.cpp"):
        return source[:-len(".hip.cpp")] + ".hsaco"
    return pathlib.Path(source).name + ".hsaco"


def symbol_part(value):
    return re.sub(r"[^A-Za-z0-9_]", "_", value)


def unique_sources():
    return sorted({kernel["source"] for kernel in KERNELS})


def write_catalog(output, entries):
    with output.open("w", encoding="utf-8") as f:
        f.write("// Generated by generate_hrx_kernels.py. Do not edit.\n")
        f.write('#include "kernels/hrx_kernel_catalog.h"\n')
        f.write("#include <cstring>\n\n")

        written_symbols = set()
        for entry in entries:
            if entry["data_symbol"] in written_symbols:
                continue
            written_symbols.add(entry["data_symbol"])
            data = entry["data"]
            f.write(f"alignas(16) static const unsigned char {entry['data_symbol']}[] = {{\n")
            for i in range(0, len(data), 12):
                chunk = data[i:i + 12]
                f.write("    ")
                f.write(", ".join(f"0x{value:02x}" for value in chunk))
                f.write(",\n")
            f.write("};\n\n")

        f.write("static const ggml_hrx_kernel_entry k_hrx_kernel_catalog[] = {\n")
        for entry in entries:
            wx, wy, wz = entry["workgroup_size"]
            executable_format = entry["format"]
            executable_format_c = "nullptr" if not executable_format else f'"{executable_format}"'
            f.write("    {\n")
            f.write(f'        "{entry["name"]}",\n')
            f.write(f'        "{entry["gfx_target"]}",\n')
            f.write(f"        {entry['data_symbol']},\n")
            f.write(f"        sizeof({entry['data_symbol']}),\n")
            f.write(f"        {executable_format_c},\n")
            f.write(f"        {entry['binding_count']},\n")
            f.write(f"        {entry['parameter_count']},\n")
            f.write(f"        {entry['constants_size']},\n")
            f.write(f"        {{ {wx}, {wy}, {wz} }},\n")
            f.write("    },\n")
        f.write("};\n\n")

        f.write("const ggml_hrx_kernel_entry * ggml_hrx_kernel_catalog_entries(size_t * count) {\n")
        f.write("    if (count) {\n")
        f.write("        *count = sizeof(k_hrx_kernel_catalog) / sizeof(k_hrx_kernel_catalog[0]);\n")
        f.write("    }\n")
        f.write("    return k_hrx_kernel_catalog;\n")
        f.write("}\n\n")

        f.write("const ggml_hrx_kernel_entry * ggml_hrx_kernel_catalog_find(const char * name, const char * gfx_target) {\n")
        f.write("    if (!name || !gfx_target) {\n")
        f.write("        return nullptr;\n")
        f.write("    }\n")
        f.write("    size_t count = 0;\n")
        f.write("    const ggml_hrx_kernel_entry * entries = ggml_hrx_kernel_catalog_entries(&count);\n")
        f.write("    for (size_t i = 0; i < count; ++i) {\n")
        f.write("        if (std::strcmp(entries[i].name, name) == 0 && std::strcmp(entries[i].gfx_target, gfx_target) == 0) {\n")
        f.write("            return &entries[i];\n")
        f.write("        }\n")
        f.write("    }\n")
        f.write("    return nullptr;\n")
        f.write("}\n")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--arch", action="append", default=[])
    parser.add_argument("--source-dir", required=True)
    parser.add_argument("--hsaco-root", default="")
    parser.add_argument("--output", required=True)
    parser.add_argument("--list-sources", action="store_true")
    args = parser.parse_args()

    source_dir = pathlib.Path(args.source_dir)
    if args.list_sources:
        for source in unique_sources():
            print(source_dir / source)
        return 0

    output = pathlib.Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)

    if not args.arch:
        sys.stderr.write("error: at least one --arch is required\n")
        return 1
    if not args.hsaco_root:
        sys.stderr.write("error: --hsaco-root is required\n")
        return 1

    hsaco_root = pathlib.Path(args.hsaco_root)
    entries = []
    hsaco_cache = {}
    for arch in args.arch:
        for kernel in KERNELS:
            source = kernel["source"]
            key = (arch, source)
            if key not in hsaco_cache:
                hsaco = hsaco_root / arch / hsaco_name_for_source(source)
                if not hsaco.exists():
                    sys.stderr.write(f"error: expected compiled HRX kernel object not found: {hsaco}\n")
                    return 1
                hsaco_cache[key] = {
                    "symbol": f"k_hrx_kernel_{symbol_part(arch)}_{len(hsaco_cache)}",
                    "data": hsaco.read_bytes(),
                }

            entry = dict(kernel)
            entry["gfx_target"] = arch
            entry["parameter_count"] = kernel.get("parameter_count", kernel["binding_count"] + 1)
            entry["data_symbol"] = hsaco_cache[key]["symbol"]
            entry["data"] = hsaco_cache[key]["data"]
            entries.append(entry)

    write_catalog(output, entries)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
